// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `postgresql://${process.env.MASTER_DATABASE_USER}:${process.env.MASTER_DATABASE_PASSWORD}@${process.env.MASTER_DATABASE_HOST}:${process.env.MASTER_DATABASE_PORT}/${process.env.MASTER_DATABASE_NAME}`,
  },
});
